export const techStacks = [
  {
    id: 'javascript',
    title: 'JavaScript',
    description: '웹의 기초가 되는 프로그래밍 언어',
    features: ['동적 타입', '프로토타입 기반', '이벤트 주도 프로그래밍'],
    benefits: '웹 브라우저에서 동작하는 유일한 프로그래밍 언어',
    img: '/js.svg',
  },
  {
    id: 'typescript',
    title: 'TypeScript',
    description: 'JavaScript에 정적 타입을 추가한 언어',
    features: ['정적 타입 시스템', '객체 지향 프로그래밍', '인터페이스'],
    benefits: '더 안전하고 maintainable한 코드 작성 가능',
    img: '/ts.svg',
  },
  {
    id: 'react',
    title: 'React',
    description: '사용자 인터페이스를 만들기 위한 JavaScript 라이브러리',
    features: ['컴포넌트 기반', 'Virtual DOM', 'JSX'],
    benefits: '선언적이고 효율적인 UI 개발',
    img: '/react.svg',
  },
  {
    id: 'nextjs',
    title: 'Next.js',
    description: 'React 기반의 풀스택 프레임워크',
    features: ['서버 사이드 렌더링', '파일 기반 라우팅', 'API 라우트'],
    benefits: '최적화된 성능과 개발자 경험',
    img: '/next.svg',
  },
  {
    id: 'algorithm',
    title: 'Algorithm',
    description: '효율적인 문제 해결을 위한 논리적 접근 방법',
    features: ['자료 구조 활용', '정렬 및 탐색 알고리즘', '최적화 기법'],
    benefits: '효율적인 문제 해결 능력과 성능 향상',
    img: '/algorithm.svg',
  },
  {
    id: 'cs',
    title: 'Computer Science (Web)',
    description: '웹 개발을 위한 컴퓨터 과학 기초 지식',
    features: ['HTTP/HTTPS', '브라우저 동작 원리', 'RESTful API'],
    benefits: '웹 시스템의 원리 이해와 문제 해결 능력 강화',
    img: '/cs.svg',
  },
  {
    id: 'node',
    title: 'Node.js',
    description: '확장 가능한 네트워크 애플리케이션을 위한 JavaScript 런타임',
    features: [
      '이벤트 기반 비동기 I/O',
      'NPM 패키지 관리',
      '크로스 플랫폼 지원',
    ],
    benefits: '효율적인 서버 사이드 JavaScript 실행 환경',
    img: '/node.svg',
  },
  {
    id: 'front_tech',
    title: 'Frontend Technologies',
    description: '현대적인 프론트엔드 개발을 위한 핵심 기술',
    features: [
      'React Query - 서버 상태 관리',
      'Zustand - 클라이언트 상태 관리',
      'Tailwind CSS - 유틸리티 기반 스타일링',
      'Framer Motion - 애니메이션',
      'React Hook Form - 폼 관리',
    ],
    benefits: '효율적이고 현대적인 프론트엔드 개발 경험',
    img: '/front-tech.svg',
  },
  {
    id: 'backend_tech',
    title: 'Backend Technologies',
    description: '확장 가능한 백엔드 시스템 구축을 위한 기술',
    features: [
      'Socket.io - 실시간 양방향 통신',
      'Prisma - TypeScript ORM',
      'Express.js - 웹 애플리케이션 프레임워크',
      'Jest - 테스팅 프레임워크',
      'Redis - 인메모리 데이터 스토어',
    ],
    benefits: '안정적이고 확장 가능한 백엔드 시스템 구축',
    img: '/backend-tech.svg',
  },
  {
    id: 'cicd',
    title: 'CI/CD',
    description: '지속적 통합과 배포를 위한 DevOps 도구',
    features: [
      'GitHub Actions - 자동화된 워크플로우',
      'Docker - 컨테이너화',
      'AWS - 클라우드 인프라',
      'Vercel - 프론트엔드 배포',
      'Jenkins - 자동화된 빌드 및 배포',
    ],
    benefits: '자동화된 개발 프로세스와 안정적인 배포 환경',
    img: '/cicd.svg',
  },
];
