export const javascriptList = [
  {
    id: '01_1',
    title: 'Basic',
    children: [
      { id: '01_1_1', title: 'JavaScript 제어 흐름과 에러 처리' },
      { id: '01_1_2', title: 'JavaScript 반복문과 순회' },
      { id: '01_1_3', title: 'JavaScript 함수의 모든 것' },
      { id: '01_1_4', title: 'JavaScript 표현식과 연산자' },
      { id: '01_1_5', title: 'JavaScript의 숫자와 날짜' },
      { id: '01_1_6', title: 'JavaScript 텍스트 다루기' },
      { id: '01_1_7', title: 'JavaScript 배열' },
      { id: '01_1_8', title: 'JavaScript 컬렉션' },
      { id: '01_1_9', title: 'JavaScript 객체' },
      { id: '01_1_10', title: 'JavaScript 클래스' },
      { id: '01_1_11', title: 'JavaScript Promise' },
      { id: '01_1_12', title: 'JavaScript Typed Arrays' },
      { id: '01_1_13', title: 'JavaScript 반복자와 생성자' },
      { id: '01_1_14', title: 'JavaScript 메타 프로그래밍' },
      { id: '01_1_15', title: 'JavaScript 모듈' },
    ],
  },
  {
    id: '01_2',
    title: 'Intermediate',
    children: [
      { id: '01_2_1', title: 'JavaScript 프로토타입' },
      { id: '01_2_2', title: '객체 지향 프로그래밍 (OOP)' },
      { id: '01_2_3', title: 'JavaScript 클래스' },
      { id: '01_2_4', title: '객체 생성 연습: 튀는 공 만들기' },
      { id: '01_2_5', title: 'Challenge: 튀는 공 데모 확장하기' },
      { id: '01_2_6', title: '비동기 JavaScript 소개' },
      { id: '01_2_7', title: 'Promise 사용하기' },
      { id: '01_2_8', title: 'Promise 기반 API 구현하기' },
    ],
  },
  {
    id: '01_3',
    title: 'Advanced',
    children: [
      { id: '01_3_1', title: '클로저(Closure)' },
      { id: '01_3_2', title: '자바스크립트 상속과 프로토타입 체인' },
      { id: '01_3_3', title: '자바스크립트 메모리 관리' },
      { id: '01_3_4', title: 'JavaScript 이벤트 루프' },
    ],
  },
];
